plugins {
    id 'com.android.application'
}

android {
    namespace 'com.tamer.honormarket'
    compileSdk 34

    defaultConfig {
        applicationId 'com.tamer.honormarket'
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName '1.0.0'
    }

    signingConfigs {
        modder {
            storeFile file('../../tools/modder.jks')
            storePassword '123456'
            keyAlias 'modder'
            keyPassword '123456'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.modder
        }
    }
}

dependencies {
    compileOnly 'de.robv.android.xposed:api:82'
}
